// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/data/blogPosts.ts
var blogPosts = [
  {
    slug: "fault-tolerant-quantum-computing-2026",
    category: "Quantum Computing",
    date: "Mar 15, 2026",
    readTime: "8 min read",
    title: "The Road to Fault-Tolerant Quantum Computing: Where Are We Now?",
    excerpt: "An in-depth look at the latest advances in quantum error correction and what they mean for practical quantum advantage.",
    author: { name: "Dr. Anika Patel", role: "Head of Quantum Research" },
    cover: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1600&q=70",
    content: [
      { type: "p", text: "Fault-tolerant quantum computing has long been the holy grail of the field. In 2026, we are closer than ever \u2014 but the journey is more nuanced than headlines suggest." },
      { type: "h2", text: "The State of Error Correction" },
      { type: "p", text: "Surface codes remain the workhorse of error correction, but new approaches like LDPC codes and bosonic encodings are showing remarkable promise. Recent demonstrations have shown logical qubit lifetimes exceeding physical qubit lifetimes by an order of magnitude." },
      { type: "h2", text: "What Practical Advantage Looks Like" },
      { type: "list", items: [
        "Logical error rates below 10\u207B\u2076 per gate",
        "Sustained operation across thousands of cycles",
        "Algorithm-specific resource estimates within engineering reach",
        "Hybrid orchestration with classical accelerators"
      ] },
      { type: "quote", text: "We're moving from 'can it work?' to 'can it scale economically?' That shift defines the next five years." },
      { type: "h2", text: "What's Next" },
      { type: "p", text: "Expect modular architectures, photonic interconnects, and tighter integration with AI co-processors. The next milestone will be a sustained, useful quantum advantage on a commercially relevant workload." }
    ]
  },
  {
    slug: "beyond-transformers-next-architecture",
    category: "AI Research",
    date: "Mar 8, 2026",
    readTime: "7 min read",
    title: "Beyond Transformers: The Next Architecture for AGI",
    excerpt: "Exploring emerging neural network architectures that could surpass transformer models in reasoning and generalization.",
    author: { name: "Dr. Marcus Rivera", role: "Principal AI Scientist" },
    cover: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1600&q=70",
    content: [
      { type: "p", text: "Transformers have dominated AI for nearly a decade, but their quadratic attention cost and weak compositional generalization leave room for successors." },
      { type: "h2", text: "Candidates on the Horizon" },
      { type: "list", items: [
        "State-space models (Mamba family) with linear-time inference",
        "Neurosymbolic hybrids combining differentiable reasoning",
        "Energy-based world models inspired by predictive coding",
        "Mixture-of-experts at extreme sparsity"
      ] },
      { type: "h2", text: "Why It Matters" },
      { type: "p", text: "Each candidate addresses a different transformer weakness. The winning architecture will likely be a synthesis \u2014 modular, efficient, and grounded in causal structure." },
      { type: "quote", text: "The next leap won't come from bigger models. It will come from better priors." }
    ]
  },
  {
    slug: "quantum-finance-2026-market-analysis",
    category: "Industry Insights",
    date: "Feb 28, 2026",
    readTime: "6 min read",
    title: "Quantum Computing in Finance: A 2026 Market Analysis",
    excerpt: "How financial institutions are deploying quantum algorithms for portfolio optimization, risk modeling, and fraud detection.",
    author: { name: "Sarah Chen", role: "Director, Financial Solutions" },
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1600&q=70",
    content: [
      { type: "p", text: "Tier-1 banks are quietly building quantum readiness teams. The use cases are narrow but lucrative \u2014 and the lead time is short." },
      { type: "h2", text: "Top Applications" },
      { type: "list", items: [
        "Portfolio optimization under realistic constraints",
        "Monte Carlo acceleration for derivatives pricing",
        "Graph-based fraud detection",
        "Post-quantum cryptography migration"
      ] },
      { type: "h2", text: "Investment Outlook" },
      { type: "p", text: "Quantum spend in financial services is projected to triple by 2028. The early winners will be firms that pair quantum pilots with AI-native infrastructure." }
    ]
  },
  {
    slug: "hybrid-quantum-classical-practical-guide",
    category: "Quantum Computing",
    date: "Feb 20, 2026",
    readTime: "9 min read",
    title: "Hybrid Quantum-Classical Systems: A Practical Guide",
    excerpt: "Best practices for designing systems that leverage both quantum and classical computing for real-world applications.",
    author: { name: "Mr. Sateesh Singh (M.Sc., MCA)", role: "CEO & Co-Founder" },
    cover: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=70",
    content: [
      { type: "p", text: "The most successful production deployments today are hybrid. Quantum handles the kernel; classical orchestrates everything else." },
      { type: "h2", text: "Design Principles" },
      { type: "list", items: [
        "Identify the smallest quantum-advantaged subroutine",
        "Minimize quantum-classical round-trips",
        "Batch and cache classical preprocessing aggressively",
        "Plan for graceful classical fallback"
      ] },
      { type: "h2", text: "Reference Architecture" },
      { type: "p", text: "A typical stack pairs a variational quantum circuit with a classical optimizer, wrapped by a queueing layer that handles backend selection, retries, and result reconciliation." },
      { type: "quote", text: "Hybrid isn't a compromise \u2014 it's the architecture." }
    ]
  },
  {
    slug: "quantum-machine-learning-hype-vs-reality",
    category: "AI Research",
    date: "Feb 12, 2026",
    readTime: "7 min read",
    title: "Quantum Machine Learning: Separating Hype from Reality",
    excerpt: "A critical analysis of where quantum ML delivers genuine speedups and where classical methods still reign supreme.",
    author: { name: "Dr. Anika Patel", role: "Head of Quantum Research" },
    cover: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=1600&q=70",
    content: [
      { type: "p", text: "QML has overpromised and underdelivered \u2014 but not uniformly. The honest picture is more interesting than either the hype or the backlash." },
      { type: "h2", text: "Where Quantum Wins" },
      { type: "list", items: [
        "Kernel methods on structured quantum data",
        "Generative modeling of quantum distributions",
        "Combinatorial feature selection"
      ] },
      { type: "h2", text: "Where Classical Wins" },
      { type: "p", text: "For tabular data, image recognition, and most NLP, classical deep learning remains overwhelmingly superior \u2014 and will likely stay that way." }
    ]
  },
  {
    slug: "quantum-talent-gap-workforce-tomorrow",
    category: "Industry Insights",
    date: "Feb 5, 2026",
    readTime: "5 min read",
    title: "The Quantum Talent Gap: Building the Workforce of Tomorrow",
    excerpt: "Strategies for organizations looking to build quantum computing capabilities and attract top-tier talent.",
    author: { name: "Marketing Team", role: "QuantumAI Lab" },
    cover: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=70",
    content: [
      { type: "p", text: "There are roughly three quantum-literate engineers for every open role. That ratio is reshaping how organizations build teams." },
      { type: "h2", text: "Recruiting Playbook" },
      { type: "list", items: [
        "Hire for fundamentals (linear algebra, optimization) over framework familiarity",
        "Partner with university labs for early-stage talent",
        "Build internal upskilling tracks for classical engineers",
        "Offer cross-domain rotations across AI, HPC, and quantum"
      ] },
      { type: "quote", text: "The best quantum hires in 2026 weren't quantum specialists in 2024." }
    ]
  }
];

// src/lib/mcp/content.ts
var SITE_URL = "https://quantumailab.lovable.app";
var company = {
  name: "QuantumAI Lab",
  tagline: "Quantum computing and AI solutions for real-world problems",
  description: "QuantumAI Lab is a technology company specializing in quantum computing and artificial intelligence. We build hybrid quantum-AI systems for healthcare, finance, logistics and other industries.",
  headquarters: "Mumbai, India",
  email: "support@quantumailab.in",
  phone: "+91-8652074439",
  leadership: "Mr. Sateesh Singh (M.Sc., MCA)",
  website: SITE_URL,
  pages: [
    { path: "/", title: "Home" },
    { path: "/about", title: "About" },
    { path: "/services", title: "Services" },
    { path: "/technology", title: "Technology" },
    { path: "/case-studies", title: "Case Studies" },
    { path: "/pricing", title: "Pricing" },
    { path: "/blog", title: "Blog" },
    { path: "/faq", title: "FAQ" },
    { path: "/contact", title: "Contact" }
  ]
};
var services = [
  {
    title: "Quantum Computing Solutions",
    description: "Custom quantum algorithms designed for optimization, simulation, and cryptography. We leverage superconducting qubits and trapped-ion systems to deliver solutions classical computers can't match.",
    features: [
      "Quantum circuit design",
      "Error correction",
      "Quantum annealing",
      "Custom qubit architectures"
    ]
  },
  {
    title: "AI & Machine Learning Development",
    description: "End-to-end AI solutions from data strategy to production deployment. Our models are built for accuracy, interpretability, and scale.",
    features: [
      "Deep learning models",
      "NLP & computer vision",
      "Reinforcement learning",
      "MLOps & deployment"
    ]
  },
  {
    title: "Hybrid Quantum-AI Systems",
    description: "The best of both worlds\u2014combining quantum speedups with classical AI for unprecedented performance on complex tasks.",
    features: [
      "Variational quantum circuits",
      "Quantum-enhanced optimization",
      "Hybrid training pipelines",
      "Performance benchmarking"
    ]
  },
  {
    title: "Research & Consulting",
    description: "Deep technical expertise to guide your quantum and AI strategy. From feasibility studies to roadmap development.",
    features: [
      "Technology assessment",
      "Proof of concept",
      "Research partnerships",
      "Talent development"
    ]
  },
  {
    title: "Enterprise Solutions",
    description: "Production-grade quantum-AI platforms tailored for enterprise scale, security, and compliance requirements.",
    features: [
      "Cloud integration",
      "Enterprise security",
      "Regulatory compliance",
      "24/7 support"
    ]
  }
];
var pricingPlans = [
  {
    name: "Starter",
    price: "$5,000",
    period: "/month",
    description: "For teams exploring quantum-AI capabilities with focused proof-of-concept projects.",
    features: [
      "Quantum algorithm consultation",
      "Single-model AI development",
      "Monthly strategy sessions",
      "Email support (48h response)",
      "Access to research reports"
    ]
  },
  {
    name: "Professional",
    price: "$15,000",
    period: "/month",
    description: "For organizations deploying quantum-AI systems in production environments.",
    features: [
      "Everything in Starter",
      "Hybrid quantum-AI pipelines",
      "Custom model training & tuning",
      "Dedicated technical lead",
      "Priority support (4h response)",
      "Quarterly performance reviews",
      "API access & integrations"
    ]
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "",
    description: "For large-scale deployments requiring dedicated infrastructure and white-glove service.",
    features: [
      "Everything in Professional",
      "Dedicated quantum hardware access",
      "On-premise deployment options",
      "Custom SLA & compliance",
      "24/7 premium support",
      "Executive briefings",
      "Talent training programs",
      "Co-research partnerships"
    ]
  }
];
var faqs = [
  {
    category: "General",
    items: [
      {
        q: "What is QuantumAI Lab?",
        a: "QuantumAI Lab is a technology company specializing in quantum computing and artificial intelligence solutions. We build hybrid quantum-AI systems that solve complex problems across industries including healthcare, finance, and logistics."
      },
      {
        q: "Where is QuantumAI Lab located?",
        a: "Our headquarters are in Mumbai, India. We serve clients globally across multiple time zones."
      },
      {
        q: "How can I get in touch?",
        a: "You can reach us via email at support@quantumailab.in, by phone at +91-8652074439, or through our contact form on the Contact page."
      }
    ]
  },
  {
    category: "Services",
    items: [
      {
        q: "What services do you offer?",
        a: "We offer quantum computing solutions, AI & machine learning development, hybrid quantum-AI systems, research & consulting, and enterprise solutions. Each service is tailored to your specific needs and scale."
      },
      {
        q: "Do you work with startups or only enterprises?",
        a: "We work with organizations of all sizes. Our Starter plan is designed for teams exploring quantum-AI capabilities, while our Enterprise plan caters to large-scale deployments."
      },
      {
        q: "Can you build custom solutions?",
        a: "Absolutely. Every engagement begins with understanding your unique challenges. We design and deliver bespoke quantum-AI solutions aligned with your business objectives."
      }
    ]
  },
  {
    category: "Pricing & Plans",
    items: [
      {
        q: "What's included in the free trial?",
        a: "The Professional plan includes a 14-day free trial with full access to hybrid quantum-AI pipelines. No credit card required to start."
      },
      {
        q: "Can I switch plans later?",
        a: "Yes. You can upgrade or downgrade at any time. Changes take effect at the start of your next billing cycle."
      },
      {
        q: "Do you offer academic or nonprofit pricing?",
        a: "We offer special pricing for academic institutions and nonprofit organizations. Contact our sales team for details."
      }
    ]
  },
  {
    category: "Technology",
    items: [
      {
        q: "What quantum hardware do you use?",
        a: "We work with leading quantum hardware providers including superconducting qubit and trapped-ion systems. Our hybrid architecture is hardware-agnostic, allowing us to leverage the best platform for each use case."
      },
      {
        q: "Is my data secure?",
        a: "Absolutely. We implement industry-standard encryption, strict access controls, and comply with relevant data protection regulations. Enterprise clients can opt for on-premise deployments."
      },
      {
        q: "What kind of support is included?",
        a: "All plans include email support. Professional plans get priority response times (4-hour SLA), and Enterprise clients receive 24/7 dedicated support with a named technical lead."
      }
    ]
  }
];

// src/lib/mcp/tools/get-blog-post.ts
function renderContent(post) {
  return post.content.map((block) => {
    switch (block.type) {
      case "h2":
        return `## ${block.text ?? ""}`;
      case "h3":
        return `### ${block.text ?? ""}`;
      case "quote":
        return `> ${block.text ?? ""}`;
      case "list":
        return (block.items ?? []).map((item) => `- ${item}`).join("\n");
      default:
        return block.text ?? "";
    }
  }).join("\n\n");
}
var get_blog_post_default = defineTool({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Get the full text of a QuantumAI Lab blog article by its slug, rendered as markdown.",
  inputSchema: {
    slug: z.string().describe("The article slug, e.g. from list_blog_posts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const post = blogPosts.find((item) => item.slug === slug.trim());
    if (!post) {
      return {
        content: [
          {
            type: "text",
            text: `No blog post found with slug "${slug}". Use list_blog_posts to see available slugs.`
          }
        ],
        isError: true
      };
    }
    const markdown = [
      `# ${post.title}`,
      `${post.category} \xB7 ${post.date} \xB7 ${post.readTime} \xB7 by ${post.author.name} (${post.author.role})`,
      renderContent(post)
    ].join("\n\n");
    return {
      content: [{ type: "text", text: markdown }],
      structuredContent: {
        slug: post.slug,
        title: post.title,
        category: post.category,
        date: post.date,
        readTime: post.readTime,
        author: post.author,
        url: `${SITE_URL}/blog/${post.slug}`,
        markdown
      }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_company_info_default = defineTool2({
  name: "get_company_info",
  title: "Get company info",
  description: "Get QuantumAI Lab's public company profile: description, headquarters, contact details, leadership, and the list of site pages.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(company, null, 2) }],
    structuredContent: { company, siteUrl: SITE_URL }
  })
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List QuantumAI Lab blog articles with slug, title, category, date, read time, excerpt and URL. Optionally filter by category or a search term.",
  inputSchema: {
    category: z2.string().describe("Optional category filter, matched case-insensitively.").optional(),
    query: z2.string().describe("Optional free-text search across title and excerpt.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query }) => {
    const term = query?.trim().toLowerCase();
    const cat = category?.trim().toLowerCase();
    const posts = blogPosts.filter((post) => cat ? post.category.toLowerCase() === cat : true).filter(
      (post) => term ? `${post.title} ${post.excerpt}`.toLowerCase().includes(term) : true
    ).map((post) => ({
      slug: post.slug,
      title: post.title,
      category: post.category,
      date: post.date,
      readTime: post.readTime,
      excerpt: post.excerpt,
      author: post.author.name,
      url: `${SITE_URL}/blog/${post.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts, null, 2) }],
      structuredContent: { posts, count: posts.length }
    };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_faqs_default = defineTool4({
  name: "list_faqs",
  title: "List FAQs",
  description: "List QuantumAI Lab's frequently asked questions and answers, optionally filtered by category (General, Services, Pricing & Plans, Technology).",
  inputSchema: {
    category: z3.string().describe("Optional category filter, matched case-insensitively.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const groups = category ? faqs.filter((group) => group.category.toLowerCase() === category.trim().toLowerCase()) : faqs;
    return {
      content: [{ type: "text", text: JSON.stringify(groups, null, 2) }],
      structuredContent: { groups }
    };
  }
});

// src/lib/mcp/tools/list-pricing-plans.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_pricing_plans_default = defineTool5({
  name: "list_pricing_plans",
  title: "List pricing plans",
  description: "List QuantumAI Lab's public pricing plans (Starter, Professional, Enterprise) with price, billing period and included features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(pricingPlans, null, 2) }],
    structuredContent: { plans: pricingPlans }
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_services_default = defineTool6({
  name: "list_services",
  title: "List services",
  description: "List the services QuantumAI Lab offers, each with a description and key capabilities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "quantumai-lab-mcp",
  title: "QuantumAI Lab",
  version: "0.1.0",
  instructions: "Public tools for QuantumAI Lab (quantum computing and AI consultancy). Use `get_company_info` for company profile and contact details, `list_services` for the service catalog, `list_pricing_plans` for plans and pricing, `list_faqs` for support questions, and `list_blog_posts` / `get_blog_post` to read published articles. All data is public marketing content; no user data is exposed.",
  tools: [get_company_info_default, list_services_default, list_pricing_plans_default, list_faqs_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
